# Generated by Django 5.1.6 on 2025-02-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
