# Generated by Django 5.1.6 on 2025-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Indefinido', max_length=100),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='Indefinido', max_length=100),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
